[WIP] change system branding
fossasia/eventyay-tickets pull request #109
Opened 2024-05-24 05:46 UTC by progmatic-99

Fixes #103 

![image](https://github.com/fossasia/eventyay-tickets/assets/42090582/20258251-89aa-48c9-8169-988dd9dbee16)
![image](https://github.com/fossasia/eventyay-tickets/assets/42090582/5eae60b0-b076-407f-84b3-1879222f02be)

2024-05-24 06:25 UTC, mariobehling requested changes
Good job as a start, but looks like you used the favicon on the top left. In any case it is too small. Please check more through your changes and see if you catch more those issues. Thanks

Current
![Screenshot from 2024-05-24 08-22-14](https://github.com/fossasia/eventyay-tickets/assets/1583873/5c84c538-af5d-423b-b277-d1399e141f2c)

Expected
![Screenshot from 2024-05-24 08-24-10](https://github.com/fossasia/eventyay-tickets/assets/1583873/126303ba-b805-4482-afe1-383e14768dfa)

2024-05-24 06:27 UTC, mariobehling commented
Ahh I see. I think because the background color is blue, the image does not appear properly. Could you please use an image with colors. Thanks.

2024-05-24 06:34 UTC, progmatic-99 commented
@mariobehling ok, doing that

2024-05-24 07:05 UTC, progmatic-99 commented
![image](https://github.com/fossasia/eventyay-tickets/assets/42090582/ae9e7533-e56c-4a32-897b-a75cf232fc45)
![image](https://github.com/fossasia/eventyay-tickets/assets/42090582/a0262c93-c4ca-4724-9aa4-f36f69a0464f)

2024-05-24 07:19 UTC, mariobehling commented
> ![image](https://private-user-images.githubusercontent.com/42090582/333486906-ae9e7533-e56c-4a32-897b-a75cf232fc45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzUzNDgsIm5iZiI6MTcxNjUzNTA0OCwicGF0aCI6Ii80MjA5MDU4Mi8zMzM0ODY5MDYtYWU5ZTc1MzMtZTU2Yy00YTMyLTg5N2ItYTc1Y2YyMzJmYzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MzI1MDc4YThiODUwYmM2ZmY0Y2JmNzRlNDU4YWY4MmRhOTdlM2M2NmI4OGM0YWY2M2M2ZDFlZGFjZjg0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gx9z-I7mpJaEEmR98p7Hch9uFfOipbVc0ipAmSznyX8) 

Could you change the background color to the same color as eventyay-talk, please?

2024-05-24 08:14 UTC, progmatic-99 commented
ok @mariobehling

2024-05-24 14:19 UTC, norbusan requested changes

2024-05-24 14:19 UTC, norbusan commented on src/pretix/control/templates/pretixcontrol/item/index.html
> +>
Can you please revert these changes, they are unrelated. You probably have your linter/ruff set to 80 char line length

2024-05-24 14:19 UTC, norbusan commented on src/pretix/control/templates/pretixcontrol/item/index.html
> +          form.name layout="control" %}
Same, that is unrelated change

2024-05-24 14:19 UTC, norbusan commented on src/pretix/control/templates/pretixcontrol/item/index.html
> +                  />
Same

2024-05-24 14:19 UTC, norbusan commented on src/pretix/control/templates/pretixcontrol/item/index.html
> +                    %}
Same

2024-05-24 14:19 UTC, norbusan commented on src/pretix/control/templates/pretixcontrol/item/index.html
> +                    people (e.g. group bundles). {% endblocktrans %}
Same

2024-05-24 14:19 UTC, norbusan commented on src/pretix/control/templates/pretixcontrol/item/index.html
> +      </div>
All of the changes in this file should be reverted, I don't think there is anything related to eventyay branding included here.

2024-05-24 14:19 UTC, norbusan commented on src/pretix/control/templates/pretixcontrol/organizers/delete.html
> +{% endif %} {% endblock %}
Same as the above, please don't include unrelated changes

2024-05-24 14:19 UTC, norbusan commented on src/pretix/static/pretixbase/img/pretix-logo.svg
The size of the images don't match, is this a problem?

2024-05-24 20:57 UTC, mariobehling commented on src/pretix/static/pretixbase/img/pretix-icon-colored.svg
Please make it same 150px x 150px even though it is a svg. If possible crop to the actual image.

2024-05-24 20:57 UTC, mariobehling commented on src/pretix/static/pretixbase/img/pretix-icon.svg
150px x150 px and crop to actual image, please.

2024-05-24 20:58 UTC, mariobehling commented on src/pretix/static/pretixbase/img/pretix-logo.svg
Please W: 254px x H: 110px

2024-05-25 13:49 UTC, progmatic-99 commented
@AviGawande i don't see your changes

2024-05-25 13:59 UTC, AviGawande commented
@progmatic-99  raise pr to your branch.

2024-05-28 21:27 UTC, mariobehling commented on src/pretix/static/pretixbase/img/pretix-icon-colored.svg
Please rename pretix to eventyay in the image file.

2024-05-28 22:04 UTC, mariobehling requested changes

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/static/pretixbase/img/pretix-logo.svg
Please rename pretix to eventyay in the image file.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/static/pretixbase/img/pretix-icon.svg
Please rename pretix to eventyay in all image files.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/presale/templates/pretixpresale/base_footer.html
> +    Creating eventyay has been an huge effort that took many years and maintaining it is still a lot of
Please delete this paragraph and the email.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/presale/templates/pretixpresale/index.html
> +            {% blocktrans trimmed with a_attr="href='https://eventyay.com'" %}
Change to:  This is a self-hosted installation of <a {{ a_attr }}>eventyay, your open source event solution.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/plugins/returnurl/templates/returnurl/settings.html
This feature is useful if you use only the payment component of the system but build your own checkout interface for other steps.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/user/2fa_enable.html
> +            {% trans "You will no longer be able to log in to eventyay without one of your configured devices." %}
Change to: You will no longer be able to log in without one of your configured devices.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/multi_languages_widget.html
> +        <span class="label label-warning" data-toggle="tooltip" title="{% trans "This translation is not maintained by the eventyay team. We cannot vouch for its correctness and new or recently chang
This translation is community-maintained and requires further verification by additional translators. New or recently updated features may not be translated yet and will appear in English.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/items/quotas.html
> +            your product eventyay will sell. This way, you can configure whether your event can take an unlimited
Change the entire paragraph as follows: 

To ensure your products are available as intended, you need to set quotas. Quotas determine how many instances of your product can be sold on the platform. This allows you to configure whether your event can accommodate an unlimited number of attendees or if the number of attendees is capped. You can assign a product to multiple quotas to meet more complex requirements, such as limiting the total number of tickets sold while also restricting the number of specific ticket types simultaneously.

2024-05-28 22:04 UTC, mariobehling commented on doc/_templates/index.html
> +            <p>Go here to find information on how to configure and use eventyay as an event organizer.</p>
Go here to find information on how to configure and use the platform as an event organizer.

2024-05-28 22:04 UTC, mariobehling commented on doc/_templates/index.html
> +            <p>Documentation and details on plugins that ship with eventyay or are officially supported.</p>
Documentation and details on plugins that ship with the platform or are officially supported.

2024-05-28 22:04 UTC, mariobehling commented on doc/_templates/index.html
> +            <p>pretix.eu is the central entry-point to the eventyay project and also the home of the commercial hosting
eventyay.com is your gateway to the eventyay project, offering premier commercial hosting services all in one place.

2024-05-28 22:04 UTC, mariobehling commented on doc/_templates/index.html
> +            <p>Our main source code repository contains all code that is part of eventyay as well as some plugins and the
The source code repository contains the code that is part of eventyay tickets as well as other components, plugins and the

2024-05-28 22:04 UTC, mariobehling commented on doc/_templates/index.html
> +            <p>This important information source contains all release notes for all stable releases of eventyay as well as
This essential resource provides all release notes for stable eventyay releases, along with general news and updates.

2024-05-28 22:04 UTC, mariobehling commented on doc/admin/config.rst
>      plugins_default=pretix.plugins.sendmail,pretix.plugins.statistics
What about changing pretix here? If this is not easily possible please open an issue describing what needs to be done to change "pretix" here.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/auth/oauth_authorization.html
> +                    eventyay account?
Do you really want to grant the application access to your account?

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/auth/oauth_authorization.html
> +                    eventyay account happens at your own risk.
This application has been reviewed, but granting access to your account is at your own risk.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/base.html
> +                                    Starting with version 1.2.0, system automatically checks for updates in the background.
The system automatically checks for updates in the background.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/event/delete.html
> +                eventyay does not allow deleting orders once they have been placed in order to be audit-proof and
To ensure audit compliance and maintain trust with financial authorities, deleting orders once they have been placed is not permitted.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/event/widget.html
> +            The eventyay widget is a way to embed your ticket shop into your event website. This way, your visitors can
A widget allows you to embed your ticket shop directly into your event website. This enables your visitors to purchase tickets instantly without leaving your site.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/item/create.html
> +                                    By default, eventyay will only ask for attendee information and offer ticket downloads for these products.
By default, the system will request attendee information and provide ticket downloads for these products.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/item/create.html
> +                                    A product that does not represent a person. By default, eventyay will not ask for attendee information or offer
For products that do not require a person to be present, such as a T-shirt, the system will, by default, not request attendee information or provide ticket downloads.

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/control/templates/pretixcontrol/organizers/team_members.html
>                          To add a new user, you can enter their email address here. If they already have a
If they already have a -> If they already have an

2024-05-28 22:04 UTC, mariobehling commented on src/pretix/settings.py
> +PRETIX_INSTANCE_NAME = config.get('pretix', 'instance_name', fallback='eventyay')
Can this be changed from "PRETIX_INSTANCE_NAME" to "NSTANCE_NAME" and the following items as well?

If this is a big complicated please open a separate issue about this.

2024-05-29 18:34 UTC, mariobehling commented on doc/development/api/email.rst
> +   Name of the pretix installation (``settings.INSTANCE_NAME``)
change to "eventyay tickets installation"

2024-05-29 18:37 UTC, mariobehling commented on src/pretix/testutils/settings.py
> +INSTANCE_NAME = 'pretix.eu'
eventyay.com

2024-05-29 18:37 UTC, mariobehling commented on src/tests/presale/test_event.py
> +        self.assertIn('-//pretix//%s//' % settings.INSTANCE_NAME, ical, 'incorrect PRODID')
Can this be renamed to "eventyay" ?

2024-05-31 16:55 UTC, progmatic-99 commented on doc/development/api/email.rst
> +   Name of the pretix installation (``settings.INSTANCE_NAME``)
done

2024-06-10 16:39 UTC, mariobehling commented
Ok, the Django 21 PR has been finally merged. Need to test if this PR works after those changes. Looks good to me in general.

2024-06-10 16:42 UTC, mariobehling approved these changes

2024-06-11 01:51 UTC, merged