Perform Dependency Upgrades and System Fixes
fossasia/eventyay-tickets pull request #248
Opened 2024-07-18 04:52 UTC by lcduong

Perform the following upgrades and maintenance

> * [ ]  Replace slimit with https://pypi.org/project/rjsmin/
> * [ ]  Upgrade jQuery
> * [ ]  PDF: Upgrade fabric.js
> * [ ]  Upgrade package-lock to v2
> * [ ]  Get rid of unmaintained dependency python-u2flib-server
> * [ ]  Upgrade NodeJS
> * [ ]  Improve npm install call in pyproject.toml (previously setup.py)
> * [ ]  Update webauthn requirement from to ==2.0
> * [ ]  Update django-oauth-toolkit requirement to ==2.3.
> * [ ]  Upgrade celery to 5.4.*
> * [ ]  chardet to 5.2.*
> * [ ]  css-inline to 0.14.*
> * [ ]  django-bootstrap3 to 24.2
> * [ ]  django-compressor to 4.5
> * [ ]  django-countries to 7.6.*
> * [ ]  django-filter to 24.2
> * [ ]  django-formtools to 2.5.1
> * [ ]  django-hierarkey to 1.2.*
> * [ ]  django-hijack 3.5.*
> * [ ]  django-otp	1.5.*
> * [ ]  django-phonenumber-field	7.3.*
> * [ ]  django-statici18n	2.5.*
> * [ ]  djangorestframework	3.15.*
> * [ ]  importlib_metadata	8.*
> * [ ]  libsass	0.23.*
> * [ ]  markdown	3.6
> * [ ]  Pillow	10.3.*
> * [ ]  protobuf	5.27.*
> * [ ]  pycparser	2.22
> * [ ]  python-dateutil	2.9.*
> * [ ]  reportlab	4.2.*
> * [ ]  stripe	7.9.*
> * [ ]  tqdm	4.66.*
> * [ ]  webauthn	2.2.*
> * [ ]  fakeredis	2.23.*
> * [ ]  flake8	7.1.*
> * [ ]  isort	5.13.*
> * [ ]  pep8-naming	0.14.*
> * [ ]  pytest	8.2.*
> * [ ]  pytest-mock	3.14.*
> * [ ]  pytest-rerunfailures	14.*
> * [ ]  pytest-xdist	3.6.*

2024-07-22 06:30 UTC, mariobehling commented
@sourcery-ai review

2024-09-24 12:38 UTC, mariobehling requested changes
Could you please split this PR into two:
a) all system upgrades
b) all changes from pretix.eu to eventyay.com

2024-09-24 12:38 UTC, mariobehling commented on doc/admin/scaling.rst
> +.. _object storage cluster: https://behind.eventyay.com/2018/03/20/high-available-cdn/
Do not change this.

2024-09-25 05:01 UTC, lcduong commented
hi @mariobehling, conflict is solved

2024-09-26 07:29 UTC, merged