Upgrade Django 3.2
fossasia/eventyay-tickets pull request #34
Opened 2024-02-12 19:42 UTC by hthungdot

2024-02-13 20:27 UTC, NaviRocker commented
Hi @hthungdot, I noticed that you are new to contributions. That's a great start! However, I would like to offer some advice. Before submitting a pull request, please claim the issue and refer to it in the pull request's description. Additionally, provide some information on what exactly you have done. This will make it easier for the reviewer to assess. Once again, best of luck with your upcoming contributions. Cheers!

2024-02-15 03:35 UTC, hongquan requested changes

2024-02-15 03:35 UTC, hongquan commented on src/pretix/api/serializers/order.py
> +                except:
Please use more specfic error class with `except`. Don't use bare `except` or `except Exception`.

2024-02-15 03:35 UTC, hongquan commented on src/pretix/api/serializers/order.py
> +                    except:
Same here for `except`.

2024-02-16 11:20 UTC, eMBee commented
how did you install django 3.2 to test this? the requirements files have not been updated to reflect the new versions needed. see src/requirements/*.txt

2024-02-16 13:47 UTC, hthungdot commented
@eMBee This pull request is not finished, but I committed what I have done so far. I hope someone else can finish it.

2024-02-16 19:03 UTC, eMBee commented
> @eMBee This pull request is not finished, but I committed what I have done so far. I hope someone else can finish it.

ok, no worries. could you outline which steps you took to get this far? i think it would help me and others to continue the work if we know how you created the current patch.

2024-02-17 03:43 UTC, hongquan requested changes

2024-02-17 03:43 UTC, hongquan commented on src/pretix/presale/urls.py
> +import pretix.presale.views.customer
This "customer" module doesn't exist.
Don't know how you come up with the name of the views imported from it.

2024-02-28 10:46 UTC, closed without merging